/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.Article

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param totalResults 
 * @param status 
 * @param articles 
 */
@Serializable

data class ArticleList (

    @SerialName(value = "totalResults") @Required val totalResults: kotlin.Int,

    @SerialName(value = "status") val status: kotlin.String? = null,

    @SerialName(value = "articles") val articles: kotlin.collections.List<Article>? = null

)

