/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.Source

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param url 
 * @param source 
 * @param author 
 * @param title 
 * @param description 
 * @param urlToImage 
 * @param publishedAt 
 * @param content 
 */
@Serializable

data class Article (

    @SerialName(value = "url") @Required val url: kotlin.String,

    @SerialName(value = "source") val source: Source? = null,

    @SerialName(value = "author") val author: kotlin.String? = null,

    @SerialName(value = "title") val title: kotlin.String? = null,

    @SerialName(value = "description") val description: kotlin.String? = null,

    @SerialName(value = "urlToImage") val urlToImage: kotlin.String? = null,

    @SerialName(value = "publishedAt") val publishedAt: kotlin.String? = null,

    @SerialName(value = "content") val content: kotlin.String? = null

)

