/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.apis.ArticlesApi
import org.openapitools.client.models.ArticleList
import org.openapitools.client.models.ErrorModel

class ArticlesApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ArticlesApi
        //val apiInstance = ArticlesApi()

        // to test everythingGet
        should("test everythingGet") {
            // uncomment below to test everythingGet
            //val category : kotlin.String = category_example // kotlin.String | Theme of news
            //val from : kotlin.String = from_example // kotlin.String | date
            //val sortBy : kotlin.String = sortBy_example // kotlin.String | Sort
            //val language : kotlin.String = language_example // kotlin.String | Language in two letters
            //val apiKey : kotlin.String = apiKey_example // kotlin.String | API key
            //val page : kotlin.Int = 56 // kotlin.Int | number of page
            //val result : ArticleList = apiInstance.everythingGet(category, from, sortBy, language, apiKey, page)
            //result shouldBe ("TODO")
        }

    }
}
