/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.apis

import org.openapitools.client.models.ArticleList
import org.openapitools.client.models.ErrorModel

import org.openapitools.client.infrastructure.*
import io.ktor.client.HttpClient
import io.ktor.client.HttpClientConfig
import io.ktor.client.request.forms.formData
import io.ktor.client.engine.HttpClientEngine
import kotlinx.serialization.json.Json
import io.ktor.http.ParametersBuilder
import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

open class ArticlesApi : ApiClient {

    constructor(
        baseUrl: String = ApiClient.BASE_URL,
        httpClientEngine: HttpClientEngine? = null,
        httpClientConfig: ((HttpClientConfig<*>) -> Unit)? = null,
        jsonSerializer: Json = ApiClient.JSON_DEFAULT
    ) : super(baseUrl = baseUrl, httpClientEngine = httpClientEngine, httpClientConfig = httpClientConfig, jsonBlock = jsonSerializer)

    constructor(
        baseUrl: String,
        httpClient: HttpClient
    ): super(baseUrl = baseUrl, httpClient = httpClient)

    /**
     * News List
     * 
     * @param category Theme of news
     * @param from date
     * @param sortBy Sort
     * @param language Language in two letters
     * @param apiKey API key
     * @param page number of page (optional)
     * @return ArticleList
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun everythingGet(category: kotlin.String, from: kotlin.String, sortBy: kotlin.String, language: kotlin.String, apiKey: kotlin.String, page: kotlin.Int? = null): HttpResponse<ArticleList> {

        val localVariableAuthNames = listOf<String>()

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        category?.apply { localVariableQuery["category"] = listOf("$category") }
        from?.apply { localVariableQuery["from"] = listOf("$from") }
        sortBy?.apply { localVariableQuery["sortBy"] = listOf("$sortBy") }
        language?.apply { localVariableQuery["language"] = listOf("$language") }
        apiKey?.apply { localVariableQuery["apiKey"] = listOf("$apiKey") }
        page?.apply { localVariableQuery["page"] = listOf("$page") }
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/top-headlines/",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }


}
