/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.ArticleList
import org.openapitools.client.models.Article

class ArticleListTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ArticleList
        //val modelInstance = ArticleList()

        // to test the property `totalResults`
        should("test totalResults") {
            // uncomment below to test the property
            //modelInstance.totalResults shouldBe ("TODO")
        }

        // to test the property `status`
        should("test status") {
            // uncomment below to test the property
            //modelInstance.status shouldBe ("TODO")
        }

        // to test the property `articles`
        should("test articles") {
            // uncomment below to test the property
            //modelInstance.articles shouldBe ("TODO")
        }

    }
}
